apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-lab.fullname" . }}
  labels:
    {{- include "hello-lab.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
